name: sstar
channels:
        - conda-forge
        - bioconda
dependencies:
        - demes
        - msprime
        - numpy
        - pandas
        - pip
        - python=3.8
        - scikit-allel
        - scipy
        - snakemake
        - statsmodels
        - r-base=4.1.2
        - r-essentials=4.1
        - rpy2
        - pyyaml
        - pip:
                - sstar
