name: sstar-dev
channels:
        - conda-forge
        - bioconda
dependencies:
        - demes
        - msprime
        - numpy
        - pandas
        - pip
        - python=3.9
        - pybedtools
        - scikit-allel
        - scikit-learn
        - scipy
        - snakemake
        - statsmodels
        - pyyaml
        - pip:
                - .
