site_name: sstar
site_url: "https://xin-huang.github.io/sstar"
repo_url: "https://github.com/xin-huang/sstar"
edit_uri: ""
docs_dir: 'docs'
theme:
  name: "material"
  features:
    - content.code.copy
  palette:
    primary: cyan
    accent: cyan
plugins:
  - search
  - mike:
      alias_type: redirect
markdown_extensions:
  - extra
  - tables
  - fenced_code
  - admonition
  - codehilite
extra:
  version:
    provider: mike
extra_javascript:
  - 'https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML'
nav:
- Home: 'index.md'
- User Guide: 
    - Overview: 'userguide/overview.md'
    - Training: 'userguide/train.md'
    - Inference: 'userguide/infer.md'
