# Copyright 2026 Xin Huang and Andrea Koca
#
# GNU General Public License v3.0
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, please see
#
#    https://www.gnu.org/licenses/gpl-3.0.en.html

import os
from functools import reduce
from typing import Sequence

import pandas as pd

KEY_COLUMNS = ["chrom", "start", "end", "sample"]
MATCH_RATE_COLUMN = "match_rate"
REQUIRED_COLUMNS = KEY_COLUMNS + [MATCH_RATE_COLUMN]


def _read_match_rate_file(match_rate_file: str, source_name: str) -> pd.DataFrame:
    """
    Read one match-rate file and rename its match-rate column.

    Parameters
    ----------
    match_rate_file : str
        Match-rate TSV file generated by `sstar match`.
    source_name : str
        Source name used for the renamed match-rate column.

    Returns
    -------
    pandas.DataFrame
        DataFrame containing key columns and one source-specific match-rate
        column.

    Raises
    ------
    ValueError
        If the input file does not contain the required columns.
    """
    match_rates = pd.read_csv(
        match_rate_file,
        sep="\t",
        header=None,
        names=REQUIRED_COLUMNS,
        keep_default_na=False,
        dtype={"chrom": str, "sample": str},
    )
    missing_columns = [
        col for col in REQUIRED_COLUMNS if col not in match_rates.columns
    ]
    if missing_columns:
        missing = ", ".join(missing_columns)
        raise ValueError(f"Match-rate file {match_rate_file} is missing: {missing}")

    match_rates = match_rates.loc[:, REQUIRED_COLUMNS].copy()
    return match_rates.rename(columns={MATCH_RATE_COLUMN: source_name})


def _assigned_source(row: pd.Series, source_names: Sequence[str]) -> str | None:
    """
    Return the source with the unique maximum match rate for one tract.

    Parameters
    ----------
    row : pandas.Series
        Row containing source-specific numeric match rates.
    source_names : sequence of str
        Source names corresponding to match-rate columns.

    Returns
    -------
    str or None
        Source name with the unique maximum match rate, or None when no unique
        maximum exists.
    """
    rates = row.loc[list(source_names)].dropna()
    if rates.empty:
        return None

    max_rate = rates.max()
    max_sources = rates.index[rates == max_rate]
    if len(max_sources) != 1:
        return None

    return str(max_sources[0])


def assign_source_by_match_rate(
    match_rate_files: Sequence[str],
    source_names: Sequence[str],
    output_prefix: str,
) -> None:
    """
    Assign inferred tracts to the source with the unique maximum match rate.

    Only tracts present in every match-rate file are considered. Missing and
    non-numeric match-rate values do not participate in the maximum comparison.
    If no unique maximum exists, the tract is not written to any source-specific
    BED file. One BED file is always generated for each source name, even if no
    tracts are assigned to that source.

    Parameters
    ----------
    match_rate_files : sequence of str
        Match-rate TSV files generated by `sstar match`.
    source_names : sequence of str
        Source names corresponding to ``match_rate_files``.
    output_prefix : str
        Prefix for source-specific BED output files.

    Raises
    ------
    ValueError
        If fewer than two match-rate files are provided, if the number of files
        does not match the number of source names, or if source names are not
        unique, or if source names use reserved column names.
    """
    if len(match_rate_files) < 2:
        raise ValueError("At least two match-rate files are required.")
    if len(match_rate_files) != len(source_names):
        raise ValueError(
            "The number of match-rate files must match source names "
            f"(got {len(match_rate_files)} match-rate files and "
            f"{len(source_names)} source names)."
        )
    if len(set(source_names)) != len(source_names):
        raise ValueError("Source names must be unique.")
    reserved_names = set(REQUIRED_COLUMNS)
    reserved_source_names = sorted(set(source_names) & reserved_names)
    if reserved_source_names:
        reserved = ", ".join(reserved_source_names)
        raise ValueError(f"Source names cannot use reserved column names: {reserved}")

    source_frames = [
        _read_match_rate_file(match_rate_file, source_name)
        for match_rate_file, source_name in zip(match_rate_files, source_names)
    ]
    merged = reduce(
        lambda left, right: pd.merge(left, right, on=KEY_COLUMNS, how="inner"),
        source_frames,
    )

    for source_name in source_names:
        merged[source_name] = pd.to_numeric(merged[source_name], errors="coerce")

    if merged.empty:
        assigned_sources = pd.Series(dtype=object)
    else:
        assigned_sources = merged.apply(
            _assigned_source, axis=1, source_names=source_names
        )

    output_dir = os.path.dirname(output_prefix)
    if output_dir:
        os.makedirs(output_dir, exist_ok=True)

    for source_name in source_names:
        output_file = f"{output_prefix}.{source_name}.bed"
        rows = merged.loc[assigned_sources == source_name, KEY_COLUMNS + [source_name]]
        rows.to_csv(output_file, sep="\t", header=False, index=False)
