# Apache License Version 2.0
# Copyright 2022 Xin Huang
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import allel
import gzip
import os
import queue
import numpy as np
import pandas as pd
from multiprocessing import Process, Queue
from typing import Iterable, Optional, Tuple, Union
from sstar.utils import read_data, py2round, read_mapped_region_file, cal_matchpct


def calc_match_pct(
    x: Union[float, list, np.ndarray],
    y: Union[float, list, np.ndarray],
    P: int = 2,
) -> Union[float, str]:
    """
    Calculate dosage-based match rate between two genotype dosage arrays.

    Missing values must be encoded as `-1` and are ignored.

    Parameters
    ----------
    x : float, list, or numpy.ndarray
        ALT-allele dosage values for the first genotype vector.
    y : float, list, or numpy.ndarray
        ALT-allele dosage values for the second genotype vector.
    P : int, optional
        Ploidy used to normalize dosage differences. Default: `2`.

    Returns
    -------
    float or str
        Mean match rate in `[0, 1]`, or `"NA"` if there are no callable sites.
    """
    x = np.atleast_1d(np.asarray(x, dtype=float))
    y = np.atleast_1d(np.asarray(y, dtype=float))

    ok = (x >= 0) & (y >= 0)
    if not np.any(ok):
        return "NA"

    return float(np.mean(1.0 - np.abs(x[ok] - y[ok]) / float(P)))


def _dosage_for_positions(
    gt: allel.GenotypeArray,
    pos: Union[list, np.ndarray],
    ind_index: int,
    positions: list,
) -> np.ndarray:
    """
    Return ALT dosage for one individual at exact genomic positions.

    If a requested position is absent or the genotype is missing, the returned dosage is `-1`.

    Parameters
    ----------
    gt : allel.GenotypeArray
        Genotype array with variant, sample, and ploidy axes.
    pos : list or numpy.ndarray
        Variant positions corresponding to `gt`.
    ind_index : int
        Index of the individual to extract.
    positions : list
        Genomic positions to query.

    Returns
    -------
    numpy.ndarray
        Dosage array aligned to `positions`.
    """
    pos = np.asarray(pos)
    gt_arr = np.asarray(gt)

    pos_to_i = {int(p): i for i, p in enumerate(pos)}

    # Positions absent from a variant-only VCF are treated as homozygous reference (dosage 0)
    out = np.zeros(len(positions), dtype=float)
    idx = []
    out_i = []

    for j, p in enumerate(positions):
        i = pos_to_i.get(int(p))
        if i is not None:
            idx.append(i)
            out_i.append(j)

    if not idx:
        return out

    idx = np.asarray(idx, dtype=int)
    out_i = np.asarray(out_i, dtype=int)

    # Keep sample axis: (k, 1, ploidy)
    sub = gt_arr[idx, ind_index : ind_index + 1, :]

    g = allel.GenotypeArray(sub)  # (k, 1, ploidy)
    dos = g.to_n_alt().astype(float)  # (k, 1)
    dos[g.is_missing()] = -1

    out[out_i] = dos[:, 0]
    return out


# @profile
def cal_match_pct(
    vcf: str,
    ref_ind_file: str,
    tgt_ind_file: str,
    src_ind_file: str,
    anc_allele_file: Optional[str],
    output: str,
    thread: int,
    score_file: str,
    mapped_region_file: Optional[str],
    phased: bool = False,  # NEW: phased/unphased flag
) -> None:
    """
    Calculate source-match rates for S* haplotypes or dosage-based S* SNP sets.

    Parameters
    ----------
    vcf : str
        Path to the VCF file containing genotype data.
    ref_ind_file : str
        Path to the file containing reference individual IDs.
    tgt_ind_file : str
        Path to the file containing target individual IDs.
    src_ind_file : str
        Path to the file containing source individual IDs.
    anc_allele_file : str or None
        Path to the ancestral allele file. If None, ancestral allele information is not used.
    output : str
        Path to the output match-rate file.
    thread : int
        Number of worker processes.
    score_file : str
        Path to the score file generated by `sstar score`.
    mapped_region_file : str or None
        Path to the BED file containing mapped regions. If None, full windows are treated as mapped.
    phased : bool, optional
        If True, use haplotype-based matching; otherwise use dosage-based matching. Default: `True`.
    """

    ref_data, ref_samples, tgt_data, tgt_samples, src_data, src_samples = read_data(
        vcf, ref_ind_file, tgt_ind_file, src_ind_file, anc_allele_file
    )

    chr_names = ref_data.keys()

    mapped_intervals = read_mapped_region_file(mapped_region_file)
    data, windows, samples, score_col = _read_score_file(
        score_file, chr_names, tgt_samples
    )
    sample_size = len(samples)

    header = "chrom\tstart\tend\tsample\thap_index\tmatch_rate\tsrc_sample"

    if thread > 1:
        thread = min(os.cpu_count() - 1, sample_size, thread)

    res = _cal_tgt_match_pct_manager(
        data,
        mapped_intervals,
        samples,
        tgt_samples,
        src_samples,
        tgt_data,
        src_data,
        sample_size,
        thread,
        phased,  # NEW
        score_col,
    )

    with open(output, "w") as o:
        o.write(header + "\n")
        o.write("\n".join(res) + "\n")


# @profile
def _read_score_file(
    score_file: str, chr_names: Iterable[str], tgt_samples: list
) -> Tuple[dict, dict, list, dict]:
    """
    Read S* score rows used for source-match-rate calculation.

    Parameters
    ----------
    score_file : str
        Path to the score file generated by `sstar score`.
    chr_names : iterable of str
        Chromosome names to initialize in the window index.
    tgt_samples : list
        Target sample IDs to retain from the score file.

    Returns
    -------
    tuple
        Tuple containing score rows by sample, windows by chromosome, retained sample IDs, and score-file column indices.
    """

    data = dict()
    windows = dict()
    for c in chr_names:
        windows[c] = []
    samples = []
    with open(score_file, "r") as f:
        header = f.readline().rstrip().split("\t")
        col = {name: i for i, name in enumerate(header)}
        for line in f.readlines():
            line = line.rstrip()
            elements = line.split("\t")
            chr_name = elements[col["chrom"]]
            win_start = elements[col["start"]]
            win_end = elements[col["end"]]
            sample = elements[col["sample"]]
            if sample not in tgt_samples:
                continue
            if elements[col["S*_SNP_number"]] == "NA":
                continue
            if sample not in data.keys():
                data[sample] = []
                samples.append(sample)
            data[sample].append(line)
            windows[chr_name].append((int(win_start), int(win_end)))

    return data, windows, samples, col


def _cal_tgt_match_pct_manager(
    data: dict,
    mapped_intervals: Optional[dict],
    samples: list,
    tgt_samples: list,
    src_samples: list,
    tgt_data: dict,
    src_data: dict,
    sample_size: int,
    thread: int,
    phased: bool,  # NEW
    score_col: dict,
) -> list:
    """
    Manage multiprocessing for target-source match-rate calculation.

    Parameters
    ----------
    data : dict
        Score rows grouped by target sample.
    mapped_intervals : dict or None
        Mapped-region intervals by chromosome. If None, full windows are treated as mapped.
    samples : list
        Target samples to process.
    tgt_samples : list
        All target sample IDs in the genotype data.
    src_samples : list
        Source sample IDs in the genotype data.
    tgt_data : dict
        Target genotype data by chromosome.
    src_data : dict
        Source genotype data by chromosome.
    sample_size : int
        Number of target samples to process.
    thread : int
        Number of worker processes.
    phased : bool
        If True, use haplotype-based matching; otherwise use dosage-based matching.
    score_col : dict
        Mapping from score-file column names to column indices.

    Returns
    -------
    list
        Output lines containing match-rate results.
    """

    try:
        from pytest_cov.embed import cleanup_on_sigterm
    except ImportError:
        pass
    else:
        cleanup_on_sigterm()

    res = []
    in_queue, out_queue = Queue(), Queue()
    workers = [
        Process(
            target=_cal_tgt_match_pct_worker,
            args=(
                in_queue,
                out_queue,
                mapped_intervals,
                tgt_data,
                src_data,
                src_samples,
                len(tgt_samples),
                phased,  # NEW
                score_col,
            ),
        )
        for ii in range(thread)
    ]

    for t in samples:
        index = tgt_samples.index(t)
        in_queue.put((index, data[t]))

    try:
        for worker in workers:
            worker.start()

        # Use timeout to avoid deadlock if worker crashes
        for s in range(sample_size):
            try:
                item = out_queue.get(timeout=60)
            except queue.Empty:
                for worker in workers:
                    worker.terminate()
                raise RuntimeError("Worker produced no output (likely crashed).")

            if item != "":
                res.append(item)

        for worker in workers:
            worker.terminate()
    finally:
        for worker in workers:
            worker.join()

    return res


def _cal_tgt_match_pct_worker(
    in_queue: Queue,
    out_queue: Queue,
    mapped_intervals: Optional[dict],
    tgt_data: dict,
    src_data: dict,
    src_samples: list,
    sample_size: int,
    phased: bool,  # NEW
    score_col: dict,
) -> None:
    """
    Worker process for target-source match-rate calculation.

    Parameters
    ----------
    in_queue : multiprocessing.Queue
        Queue providing target sample indices and score rows.
    out_queue : multiprocessing.Queue
        Queue receiving formatted match-rate output.
    mapped_intervals : dict or None
        Mapped-region intervals by chromosome. If None, full windows are treated as mapped.
    tgt_data : dict
        Target genotype data by chromosome.
    src_data : dict
        Source genotype data by chromosome.
    src_samples : list
        Source sample IDs in the genotype data.
    sample_size : int
        Number of target samples in the genotype data.
    phased : bool
        If True, use haplotype-based matching; otherwise use dosage-based matching.
    score_col : dict
        Mapping from score-file column names to column indices.
    """

    while True:
        index, data = in_queue.get()
        res = _cal_match_pct_ind(
            data,
            index,
            mapped_intervals,
            tgt_data,
            src_data,
            src_samples,
            sample_size,
            phased,  # NEW
            score_col,
        )
        out_queue.put("\n".join(res))


# @profile
def _cal_match_pct_ind(
    data: list,
    tgt_ind_index: int,
    mapped_intervals: Optional[dict],
    tgt_data: dict,
    src_data: dict,
    src_samples: list,
    sample_size: int,
    phased: bool,
    score_col: dict,
) -> list:
    """
    Calculate source-match rates for one target individual.
    """
    res = []
    for line in data:
        elements = line.split("\t")
        chr_name = elements[score_col["chrom"]]
        win_start = int(elements[score_col["start"]])
        win_end = int(elements[score_col["end"]])
        sample = elements[score_col["sample"]]
        hap_index = elements[score_col["hap_index"]]

        snp_positions = [
            int(p) for p in elements[score_col["S*_SNPs"]].split(",") if p and p != "NA"
        ]

        for src_ind_index, src_sample in enumerate(src_samples):
            if phased:
                # phased output stays haplotype-based
                hap1_res = cal_matchpct(
                    chr_name, mapped_intervals, tgt_data, src_data,
                    tgt_ind_index, src_ind_index, 0, win_start, win_end, sample_size
                )
                hap2_res = cal_matchpct(
                    chr_name, mapped_intervals, tgt_data, src_data,
                    tgt_ind_index, src_ind_index, 1, win_start, win_end, sample_size
                )
                hap1_match_pct = hap1_res[-1]
                hap2_match_pct = hap2_res[-1]

                res.append(
                    f"{chr_name}\t{win_start}\t{win_end}\t{sample}\t1\t{hap1_match_pct}\t{src_sample}"
                )
                res.append(
                    f"{chr_name}\t{win_start}\t{win_end}\t{sample}\t2\t{hap2_match_pct}\t{src_sample}"
                )
            else:
                # NEW: unphased output uses dosage-based formula on S* SNP positions
                tgt_gt = tgt_data[chr_name]["GT"]
                tgt_pos = tgt_data[chr_name]["POS"]
                src_gt = src_data[chr_name]["GT"]
                src_pos = src_data[chr_name]["POS"]

                tgt_dos = _dosage_for_positions(
                    tgt_gt, tgt_pos, tgt_ind_index, snp_positions
                )
                src_dos = _dosage_for_positions(
                    src_gt, src_pos, src_ind_index, snp_positions
                )

                match_pct = calc_match_pct(tgt_dos, src_dos, P=2)

                res.append(
                    f"{chr_name}\t{win_start}\t{win_end}\t{sample}\t{hap_index}\t{match_pct}\t{src_sample}"
                )

    return res


