# Copyright 2026 Xin Huang
#
# GNU General Public License v3.0
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, please see
#
#    https://www.gnu.org/licenses/gpl-3.0.en.html

import os

import demes
import msprime

from sstar.generators import WindowDataGenerator
from sstar.feature_vector_preprocessor import FeatureVectorPreprocessor


class MsprimeSimulator:
    """
    Simulate genetic data using the msprime package.

    This class is a concrete simulator implementation. Callers construct it
    with simulation parameters and then call :meth:`run` to generate output
    files for one replicate.

    Callers can rely on:
    - initialization-time attributes such as `demo_model_file`, `nref`,
      `ntgt`, `ref_id`, `tgt_id`, `src_id`, `ploidy`, `seq_len`, `mut_rate`,
      `rec_rate`, `output_prefix`, `output_dir`, and `is_phased`
    - `run(rep=None, seed=None)`, which returns a list containing one mapping
      of output artifact paths
    """

    def __init__(
        self,
        demo_model_file: str,
        nref: int,
        ntgt: int,
        ref_id: str,
        tgt_id: str,
        src_id: str,
        ploidy: int,
        seq_len: int,
        mut_rate: float,
        rec_rate: float,
        output_prefix: str,
        output_dir: str,
        is_phased: bool,
        feature_config_file: str,
    ):
        """
        Initialize a new instance of MsprimeSimulator with specific parameters for msprime simulations.

        Parameters
        ----------
        demo_model_file : str
            Path to the demographic model file, which defines the demographic history to simulate.
        nref : int
            Number of samples in the reference population.
        ntgt : int
            Number of samples in the target population.
        ref_id : str
            Identifier for the reference population in the demographic model.
        tgt_id : str
            Identifier for the target population in the demographic model.
        src_id : str
            Identifier for the source population in the demographic model.
        ploidy : int
            Ploidy of the samples; typically 2 for diploid organisms.
        seq_len : int
            Length of the sequence to simulate, in base pairs.
        mut_rate : float
            Mutation rate per base pair per generation.
        rec_rate : float
            Recombination rate per base pair per generation.
        output_prefix : str
            Prefix for the output files generated by the simulation.
        output_dir : str
            Directory where the output files will be stored.
        is_phased : bool
            Indicates whether the true tracts should be considered as unphased.

        Notes
        -----
        This class no longer inherits simulator state from a generic base.
        All simulator state used by :meth:`run` is initialized directly in this
        constructor.
        """
        self.demo_model_file = demo_model_file
        self.nref = nref
        self.ntgt = ntgt
        self.ref_id = ref_id
        self.tgt_id = tgt_id
        self.src_id = src_id
        self.ploidy = ploidy
        self.seq_len = seq_len
        self.mut_rate = mut_rate
        self.rec_rate = rec_rate
        self.output_prefix = output_prefix
        self.output_dir = output_dir
        self.test_tgt_id = self.tgt_id
        self.is_phased = is_phased
        self.feature_config_file = feature_config_file

    def run(self, rep: int = None, seed: int = None) -> list[dict[str, object]]:
        """
        Execute the simulation with optional runtime arguments.

        Outputs multiple files including simulation results and metadata.

        Parameters
        ----------
        rep : int or None, optional
            Used to specify the replicate number for the simulation. This attribute is not set
            in the constructor but should be assigned before running simulations that require
            tracking or distinguishing between multiple replicates. Default: None.
        seed : int or None, optional
            Seed for the random number generator to ensure reproducibility of the simulations.
            Similar to `rep`, this is not directly set in the constructor but should be specified
            to ensure that simulations can be reproduced exactly. Default: None.

        Returns
        -------
        list[dict[str, object]]
            A list of per-sample feature dictionaries generated from the simulated VCF.
        """
        output_dir = (
            self.output_dir if rep is None else os.path.join(self.output_dir, str(rep))
        )
        output_prefix = (
            self.output_prefix if rep is None else f"{self.output_prefix}.{rep}"
        )

        os.makedirs(output_dir, exist_ok=True)
        ts_file = os.path.join(output_dir, f"{output_prefix}.ts")
        vcf_file = os.path.join(output_dir, f"{output_prefix}.vcf")
        ref_ind_file = os.path.join(output_dir, f"{output_prefix}.ref.ind.list")
        tgt_ind_file = os.path.join(output_dir, f"{output_prefix}.tgt.ind.list")
        seed_file = os.path.join(output_dir, f"{output_prefix}.seedmsprime")

        self._create_ref_tgt_file(self.nref, self.ntgt, ref_ind_file, tgt_ind_file)

        demo_graph = demes.load(self.demo_model_file)
        demography = msprime.Demography.from_demes(demo_graph)
        samples = [
            msprime.SampleSet(self.nref, ploidy=self.ploidy, population=self.ref_id),
            msprime.SampleSet(
                self.ntgt, ploidy=self.ploidy, population=self.test_tgt_id
            ),
        ]

        ts = msprime.sim_ancestry(
            recombination_rate=self.rec_rate,
            sequence_length=self.seq_len,
            samples=samples,
            demography=demography,
            random_seed=seed,
        )
        ts = msprime.sim_mutations(
            ts,
            rate=self.mut_rate,
            random_seed=seed,
            model=msprime.BinaryMutationModel(),
        )

        ts.dump(ts_file)
        with open(vcf_file, "w") as o:
            ts.write_vcf(o)
        if seed is not None:
            with open(seed_file, "w") as o:
                o.write(f"{seed}\n")



        window_data_generator = WindowDataGenerator(
            vcf_file=vcf_file,
            ref_ind_file=ref_ind_file,
            tgt_ind_file=tgt_ind_file,
            chr_name="1",
            win_len=self.seq_len,
            win_step=self.seq_len,
            ploidy=self.ploidy,
            is_phased=self.is_phased,
        )

        preprocessor = FeatureVectorPreprocessor(
            ref_ind_file=ref_ind_file,
            tgt_ind_file=tgt_ind_file,
            feature_config_file=self.feature_config_file,
        )

        features = preprocessor.run(**list(window_data_generator.get())[0])

        for item in features:
            item["Replicate"] = rep

        return features

    def _create_ref_tgt_file(
        self,
        nref: int,
        ntgt: int,
        ref_ind_file: str,
        tgt_ind_file: str,
        identifier: str = "tsk_",
    ) -> None:
        """
        Create files listing reference and target individual identifiers.

        Parameters
        ----------
        nref : int
            Number of reference individuals.
        ntgt : int
            Number of target individuals.
        ref_ind_file : str
            Path to the output file for reference individuals.
        tgt_ind_file : str
            Path to the output file for target individuals.
        identifier : str, optional
            Prefix for individual identifiers (default is "tsk_").
        """
        with open(ref_ind_file, "w") as f:
            for i in range(nref):
                f.write(identifier + str(i) + "\n")

        with open(tgt_ind_file, "w") as f:
            for i in range(nref, nref + ntgt):
                f.write(identifier + str(i) + "\n")
