# Copyright 2026 Xin Huang
#
# GNU General Public License v3.0
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, please see
#
#    https://www.gnu.org/licenses/gpl-3.0.en.html

import os
from typing import Any

import demes
import msprime
import numpy as np

from sstar.feature_vector_preprocessor import FeatureVectorPreprocessor
from sstar.utils import split_genome


class MsprimeSimulator:
    """
    Simulate genetic data using the msprime package.

    This class is a concrete simulator implementation. Callers construct it
    with simulation parameters and then call :meth:`run` to generate output
    files for one replicate.

    Callers can rely on:
    - initialization-time attributes such as `demo_model_file`, `nref`,
      `ntgt`, `ref_id`, `tgt_id`, `ploidy`, `seq_len`, `mut_rate`,
      `rec_rate`, `output_prefix`, `output_dir`, and `is_phased`
    - `run(rep=None, seed=None)`, which returns a list containing one mapping
      of output artifact paths
    """

    def __init__(
        self,
        demo_model_file: str,
        nref: int,
        ntgt: int,
        ref_id: str,
        tgt_id: str,
        ploidy: int,
        seq_len: int,
        mut_rate: float,
        rec_rate: float,
        output_prefix: str,
        output_dir: str,
        is_phased: bool,
        match_bonus: int,
        max_mismatch: int,
        mismatch_penalty: int,
        keep_sim_data: bool = False,
    ):
        """
        Initialize a new instance of MsprimeSimulator with specific parameters for msprime simulations.

        Parameters
        ----------
        demo_model_file : str
            Path to the demographic model file, which defines the demographic history to simulate.
        nref : int
            Number of samples in the reference population.
        ntgt : int
            Number of samples in the target population.
        ref_id : str
            Identifier for the reference population in the demographic model.
        tgt_id : str
            Identifier for the target population in the demographic model.
        ploidy : int
            Ploidy of the samples; typically 2 for diploid organisms.
        seq_len : int
            Length of the sequence to simulate, in base pairs.
        mut_rate : float
            Mutation rate per base pair per generation.
        rec_rate : float
            Recombination rate per base pair per generation.
        output_prefix : str
            Prefix for the output files generated by the simulation.
        output_dir : str
            Directory where the output files will be stored.
        is_phased : bool
            Indicates whether the true tracts should be considered as unphased.
        keep_sim_data : bool, optional
            If True, writes tree sequence and seed files for each replicate.
        """
        self.demo_model_file = demo_model_file
        self.nref = nref
        self.ntgt = ntgt
        self.ref_id = ref_id
        self.tgt_id = tgt_id
        self.ploidy = ploidy
        self.seq_len = seq_len
        self.mut_rate = mut_rate
        self.rec_rate = rec_rate
        self.output_prefix = output_prefix
        self.output_dir = output_dir
        self.test_tgt_id = self.tgt_id
        self.is_phased = is_phased
        self.match_bonus = match_bonus
        self.max_mismatch = max_mismatch
        self.mismatch_penalty = mismatch_penalty
        self.keep_sim_data = keep_sim_data

    def run(self, rep: int = None, seed: int = None) -> list[dict[str, object]]:
        """
        Execute the simulation with optional runtime arguments.

        Outputs multiple files including simulation results and metadata.

        Parameters
        ----------
        rep : int or None, optional
            Used to specify the replicate number for the simulation. This attribute is not set
            in the constructor but should be assigned before running simulations that require
            tracking or distinguishing between multiple replicates. Default: None.
        seed : int or None, optional
            Seed for the random number generator to ensure reproducibility of the simulations.
            Similar to `rep`, this is not directly set in the constructor but should be specified
            to ensure that simulations can be reproduced exactly. Default: None.

        Returns
        -------
        list[dict[str, object]]
            A list of per-sample feature dictionaries generated from the simulated tree sequence.
        """
        output_dir = (
            self.output_dir if rep is None else os.path.join(self.output_dir, str(rep))
        )
        output_prefix = (
            self.output_prefix if rep is None else f"{self.output_prefix}.{rep}"
        )

        demo_graph = demes.load(self.demo_model_file)
        demography = msprime.Demography.from_demes(demo_graph)
        samples = [
            msprime.SampleSet(self.nref, ploidy=self.ploidy, population=self.ref_id),
            msprime.SampleSet(
                self.ntgt, ploidy=self.ploidy, population=self.test_tgt_id
            ),
        ]

        ts = msprime.sim_ancestry(
            recombination_rate=self.rec_rate,
            sequence_length=self.seq_len,
            samples=samples,
            demography=demography,
            random_seed=seed,
        )
        ts = msprime.sim_mutations(
            ts,
            rate=self.mut_rate,
            random_seed=seed,
            model=msprime.BinaryMutationModel(),
        )

        if self.keep_sim_data:
            os.makedirs(output_dir, exist_ok=True)
            ts_file = os.path.join(output_dir, f"{output_prefix}.ts")
            ts.dump(ts_file)

            if seed is not None:
                seed_file = os.path.join(output_dir, f"{output_prefix}.seedmsprime")
                with open(seed_file, "w") as o:
                    o.write(f"{seed}\n")

        ref_samples, tgt_samples = self._create_ref_tgt_samples()
        preprocessor = FeatureVectorPreprocessor(
            ref_samples=ref_samples,
            tgt_samples=tgt_samples,
            match_bonus=self.match_bonus,
            max_mismatch=self.max_mismatch,
            mismatch_penalty=self.mismatch_penalty,
        )

        features = preprocessor.run(**self._build_feature_input_from_ts(ts))

        for item in features:
            item["Replicate"] = rep

        return features

    def _build_feature_input_from_ts(self, ts: Any) -> dict[str, object]:
        """Build feature-vector input arrays directly from a tree sequence.

        Parameters
        ----------
        ts : Any
            Tree sequence returned by msprime after mutation simulation.

        Returns
        -------
        dict[str, object]
            Keyword arguments for :meth:`FeatureVectorPreprocessor.run`.
        """
        pos = np.array([int(site.position) for site in ts.sites()])
        gts = ts.genotype_matrix()

        nref_haplotypes = self.nref * self.ploidy
        ref_hap_gts = gts[:, :nref_haplotypes]
        tgt_hap_gts = gts[:, nref_haplotypes:]

        ref_fixed_alt = np.sum(ref_hap_gts, axis=1) == ref_hap_gts.shape[1]
        tgt_fixed_alt = np.sum(tgt_hap_gts, axis=1) == tgt_hap_gts.shape[1]
        keep = np.logical_not(np.logical_and(ref_fixed_alt, tgt_fixed_alt))

        pos = pos[keep]
        ref_hap_gts = ref_hap_gts[keep]
        tgt_hap_gts = tgt_hap_gts[keep]

        windows = split_genome(
            pos=pos,
            chr_name="1",
            polymorphism_size=self.seq_len,
            step_size=self.seq_len,
        )
        chr_name, window_range = windows[0]
        start, end = window_range

        idx = (pos >= start) & (pos <= end)
        pos = pos[idx]
        ref_hap_gts = ref_hap_gts[idx]
        tgt_hap_gts = tgt_hap_gts[idx]

        if self.is_phased:
            ref_gts = ref_hap_gts
            tgt_gts = tgt_hap_gts
        else:
            ref_gts = ref_hap_gts.reshape((len(pos), self.nref, self.ploidy)).sum(
                axis=2
            )
            tgt_gts = tgt_hap_gts.reshape((len(pos), self.ntgt, self.ploidy)).sum(
                axis=2
            )

        return {
            "chr_name": chr_name,
            "start": start,
            "end": end,
            "ploidy": self.ploidy,
            "is_phased": self.is_phased,
            "ref_gts": ref_gts,
            "tgt_gts": tgt_gts,
            "pos": pos,
        }

    def _create_ref_tgt_samples(
        self, identifier: str = "tsk_"
    ) -> tuple[list[str], list[str]]:
        """Create reference and target sample identifiers.

        Parameters
        ----------
        identifier : str, optional
            Prefix for individual identifiers (default is ``"tsk_"``).

        Returns
        -------
        tuple[list[str], list[str]]
            Reference and target sample identifiers.
        """
        ref_samples = [f"{identifier}{i}" for i in range(self.nref)]
        tgt_samples = [
            f"{identifier}{i}" for i in range(self.nref, self.nref + self.ntgt)
        ]
        return ref_samples, tgt_samples
