# Copyright 2026 Xin Huang and Andrea Koca
#
# GNU General Public License v3.0
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, please see
#
#    https://www.gnu.org/licenses/gpl-3.0.en.html

import argparse

from sstar.assign import assign_source_by_match_rate
from sstar.parsers.argument_validation import existed_file


def _run_assign(args: argparse.Namespace) -> None:
    """
    Execute source assignment with specified parameters.

    Parameters
    ----------
    args : argparse.Namespace
        Parsed command-line arguments.
    """
    assign_source_by_match_rate(
        match_rate_files=args.match_rate,
        source_names=args.source_name,
        output_prefix=args.output_prefix,
    )


def add_assign_parser(subparsers: argparse.ArgumentParser) -> None:
    """
    Initialize and configure the assign subcommand parser.

    Parameters
    ----------
    subparsers : argparse.ArgumentParser
        Command-line subparsers to configure.
    """
    parser = subparsers.add_parser(
        "assign",
        help="Assign inferred tracts to the source with the highest match rate.",
    )
    parser.add_argument(
        "--match-rate",
        type=existed_file,
        nargs="+",
        required=True,
        help="Match-rate TSV files generated by sstar match.",
    )
    parser.add_argument(
        "--source-name",
        nargs="+",
        required=True,
        help="Source names corresponding to --match-rate files.",
    )
    parser.add_argument(
        "--output-prefix",
        required=True,
        help="Prefix for source-specific BED output files.",
    )
    parser.set_defaults(runner=_run_assign)
